# Generated by Django 4.2.3 on 2024-06-04 11:12
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_testmodel_name'),
    ]

    operations = [
        UnaccentExtension()
    ]