# Generated by Django 4.2.3 on 2024-06-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_ongoingtests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ongoingtests',
            options={'verbose_name_plural': 'Ongoing Tests'},
        ),
    ]
