# Generated by Django 4.2.3 on 2024-06-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_alter_ongoingtests_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoingtests',
            old_name='time',
            new_name='started_time',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('ended_time', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.testmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Tests',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='data.userchoice')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.testmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Answers',
            },
        ),
    ]
